# Generated by Django 4.1.5 on 2023-01-13 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flightApp.flight"
            ),
        ),
    ]
