# Generated by Django 4.1.5 on 2023-01-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0002_alter_reservation_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="middlename",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
