# Generated by Django 4.1.5 on 2023-01-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flightApp", "0003_alter_passenger_middlename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flightApp.passenger"
            ),
        ),
    ]
